FROM python:3.11-slim

WORKDIR /frontend-workspace

COPY frontend/requirements.txt ./frontend/requirements.txt


RUN pip install --no-cache-dir -r frontend/requirements.txt

COPY . .

EXPOSE 8501

ENV PYTHONPATH=/frontend-workspace

CMD ["streamlit","run","frontend/app.py","--server.port=8501","--server.address=0.0.0.0"]