FROM python:3.11-slim

WORKDIR /workspace

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

#INstall uv (Python pacakage/ dependency manager)
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

ENV PATH="/root/.local/bin:$PATH"


COPY . .

# RUN pip install --no-cache-dir uv
# 🚀 ADDED THE INDEX STRATEGY FLAG TO SOLVE THE CERTIFI LOWER-INDEX TRAP
RUN uv pip install --system --index-strategy unsafe-best-match --no-cache -r backend/requirements.txt

EXPOSE 8000

CMD ["uvicorn", "backend.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
