from logging.config import fileConfig
from sqlalchemy import engine_from_config
from sqlalchemy import pool
from alembic import context

# --- IMPORT YOUR PRODUCTION SETTINGS AND METADATA ---
from backend.app.core.config import settings
from backend.app.core.database import Base
# Import your models so Alembic registers them for autogenerate
from backend.app.models.base import * 

config = context.config

# Interpret the config file for Python logging.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Override the standard alembic.ini connection string with our dynamic URL
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

target_metadata = Base.metadata

# --- ADD THIS SYSTEM FILTER HOOK ---
def include_object(object, name, type_, reflected, compare_to):
    """
    Tells Alembic to ignore LangGraph checkpoint tables and custom HNSW 
    vector indexes so it doesn't try to drop them during autogenerate cycles.
    """
    # 1. Ignore any table generated by the LangGraph checkpoint framework
    if type_ == "table" and (name.startswith("checkpoint") or name == "checkpoint_migrations"):
        return False
        
    # 2. Ignore your manually managed HNSW pgvector search index
    if type_ == "index" and name == "chunks_embedding_hnsw":
        return False
        
    return True

def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "pyformat"},
        include_object=include_object  # <-- Register filter here
    )

    with context.begin_transaction():
        context.run_migrations()

def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection, 
            target_metadata=target_metadata,
            include_object=include_object  # <-- Register filter here
        )

        with context.begin_transaction():
            context.run_migrations()

if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()