name: Evaluation

# on: 
#   workflow_run:
#     workflows: ["CI"]
#     types:
#       - completed
# on: 
#   pull_request:
#     branches:
#       - main
on:
  push:
    branches:
      - test-eval-docker


jobs:
  evaluate:
    # if: ${{github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest

    #spin up a postges service with the pgvector installed
    services:
      postgres:
        image:  pgvector/pgvector:pg16
        env:
          POSTGRES_USER: ${{secrets.DB_USER}}
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}
          POSTGRES_DB: ${{secrets.DB_NAME}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U langgraph_user_2 -d llmops_rag_2"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    
    env:
      #PYTHONPATH: ${{ github.workspace }}: This replaces the ambiguous dot (.) with an explicit, rock-solid absolute path string (e.g., /home/runner/work/rag_llmops/rag_llmops) 
      #so Python knows exactly where the root directory sits.
      PYTHONPATH: ${{github.workspace}}
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: ${{secrets.DB_NAME}}
      DB_USER: ${{secrets.DB_USER}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      LANGCHAIN_TRACING_V2: "true"
      LANGCHAIN_API_KEY: ${{secrets.LANGSMITH_API_KEY}}
      LANGSMITH_PROJECT: ${{secrets.LANGSMITH_PROJECT}}
      LANGSMITH_API_KEY: ${{secrets.LANGSMITH_API_KEY}}
      LANGSMITH_ENDPOINT: ${{secrets.LANGSMITH_ENDPOINT}}
      HUGGINGFACE_API_KEY: ${{secrets.HUGGINGFACE_API_KEY}}
      GOOGLE_APPLICATION_CREDENTIALS: ${{github.workspace}}/gcp-credentials.json
      DATABASE_URL: postgresql+psycopg://${{secrets.DB_USER}}:${{secrets.DB_PASSWORD}}@localhost:5432/${{secrets.DB_NAME}}
      psycopg_URL: postgresql://${{secrets.DB_USER}}:${{secrets.DB_PASSWORD}}@localhost:5432/${{secrets.DB_NAME}}

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; else pip install -r requirements.txt; fi

      - name: Create GCP Credential File
        run: |
          echo '${{secrets.GCP_SA_KEY}}' > ${{github.workspace}}/gcp-credentials.json

      # 🏁 Step A: Initialize the schema and populate text chunks + episodic memories + vectors into the service container
      - name: Initialize and Seed Evaluation Database
        run: |
          python -m backend.evaluation.init_eval_db
      - name: Run RAGAS Evaluation
        run: |
          python -m backend.evaluation.evaluators.ragas_eval  

      - name: Run DeepEval Evaluation
        run: |
          python -m backend.evaluation.evaluators.deepeval_eval 

      - name: Custom metrics evaluation
        run: |
          python -m backend.evaluation.evaluators.custom_eval
        

      - name: Upload Evaluation reports
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-reports
          path: backend/evaluation/reports/ 